### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by melodykramer**

### CODE REVIEW

**Comment by melodykramer** [comment]
@vzvenyach do you have to merge these for me to see my slideshow? I'm not sure how to see it without the merge.

**Comment by adelevie** [comment]
@melodykramer do you want to view the slides locally?

If so, try one of these commands from within your `slides` folder:

```
python3 -m http.server
```

or

```
python -m HttpSimpleServer
```

Then in your browser, the slides should be visible at localhost:8080.

**Comment by melodykramer** [comment]
Thanks @adelevie - once it's finished, can I also merge here? I'll be giving a presentation tomorrow to the PIFs.

**Comment by adelevie** [comment]
> can I also merge here?

I'm not sure. Is this repo meant to be a template for us to fork, or is this a collection for different sets of slides, @vzvenyach?

@melodykramer, if you can't merge here, do the following (this will get your changes in your own repo):
1. Clone the `slides` repo if you don't already have a local copy.
2. Create a new (18F) repo.
3. Copy the repo's git URL (it'll be on the main page of your newly-created and empty repo). It will look like `git@github.com:18F/REPO-NAME.git`.
4. Run this command `git remote set-url origin GIT_URL_FROM_STEP_3`
5. Run this command `git checkout gh-pages`
6. Run this command `git merge patch-1`.
7. Test locally using the commands mentioned above.
8. Run this command to push to your repo `git push origin gh-pages`
9. In about 5-10 minutes, visit https://18f.github.io/REPO-NAME and your slides should be there.

This _should_ get you all the way there, but ping me if there are any hiccups.

**Comment by melodykramer** [comment]
Thanks @adelevie - will do!

**Comment by melodykramer** [comment]
One tiny hiccup: they're rendering, but not as slides:

http://melodykramer.github.io/18f/melodykramer/

**Comment by jackiekazil** [comment]
@melodykramer I load it just like a jekyll site.

```
jekyll serve
```

**Comment by vdavez** [comment]
@melodykramer sorry i missed this before. I am going to merge and fix for you...

**Pull request merged**
