### PR TITLE
Adds a distributed holiday party presentation

### PR DESCRIPTION
**Pull request by gboone**
cc: @carodew @bsweger @melodykramer and anyone else who was at the distributed team gathering

### CODE REVIEW

**Comment by carodew** [comment]
:+1:

**Comment by wslack** [comment]
Greg, do you mind submitting this PR to not-the-main-branch so we can evaluate the preview on Federalist?

**Comment by gboone** [comment]
This is so old I'm not sure it's worth merging anymore.

**Comment by wslack** [comment]
Fair - want to close it?

**Pull request closed without merging**
